# This file allows you to configure Airflow Connections, Pools, and Variables in a single place for local development only.
# NOTE: json dicts can be added to the conn_extra field as yaml key value pairs. See the example below.

# For more information, refer to our docs: https://www.astronomer.io/docs/astro/cli/develop-project#configure-airflow_settingsyaml-local-development-only
# For questions, reach out to: https://support.astronomer.io
# For issues create an issue ticket here: https://github.com/astronomer/astro-cli/issues

airflow:
  connections:
    - conn_id: minio
      conn_type: aws
      conn_login: minio
      conn_password: minio123
      conn_extra:
        endpoint_url: "http://minio:9000"

    - conn_id: postgres
      conn_type: postgres
      conn_host: postgres
      conn_login: postgres
      conn_password: postgres
      conn_port: 5432
      # [Note] Kept as 'postgres' type for Astro SDK compatibility.
      # [참고] Astro SDK 호환성을 위해 'postgres' 타입 유지.

    - conn_id: stock_api
      conn_type: http
      conn_host: https://query1.finance.yahoo.com
      conn_extra:
        endpoint: "/v8/finance/chart/"
        headers:
          Content-Type: "application/json"
          User-Agent: "Mozilla/5.0"
          Accept: "application/json"
  pools:
    - pool_name:
      pool_slot:
      pool_description:
  variables:
    - variable_name:
      variable_value:
